### ISSUE TITLE
om-2.0-3.3 not found 

### ISSUE THREAD

**Issue by King-GO** [itmicus/cmdbuild_docker#22]
Pulling openmaint_app (itmicus/cmdbuild:om-2.0-3.3)...
ERROR: manifest for itmicus/cmdbuild:om-2.0-3.3 not found: manifest unknown: manifest unknown

**Comment by afcarvalho1991** [comment]
I'll check it tonight! Source forge has been having access problems the last 2 days

**Comment by afcarvalho1991** [comment]
This is because itmicus has not released this image on docker. 

Please follow the instructions I provided here https://github.com/itmicus/cmdbuild_docker/issues/21

But instead, run the following commands on this project root folder

```
docker build -t itmicus/cmdbuild:om-2.0-3.3 openmaint-2.0-3.3/. --label "version=1.0" --label "maintaner=Itmicus <order@itmicus.ru>"
cd cmdbuild:om-2.0-3.3
docker-compose up

#wait a few minutes until you see something like this on your terminal

#cmdbuild_app  | 22-Oct-2020 06:47:26.231 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [86] ms
#cmdbuild_app  | 22-Oct-2020 06:47:26.266 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
#cmdbuild_app  | 22-Oct-2020 06:47:26.349 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [43,504] milliseconds
```

PS: I might update to the newer openmaint version
PS2: also note that Openmaint has currently a browser conflict and it only works well on firefox!

Best of luck!
