### ISSUE TITLE
Is there any security vulnerable in this docker setup? I got attack kdevtmpfsi

### ISSUE THREAD

**Issue by ridwankustanto** [itmicus/cmdbuild_docker#29]
Hi, so I'm trying this image, and yesterday I setup an fresh instance just for this app, and not long after that, I found my server cpu so high.

I found out that I got attack by this script called kdevtmpfsi. I searched it that it's a cryptocurrency miner script that’s utilizing your CPU.

And I deleted the first instance and setup another one, and it's happening again now.

So, how this could happen?

Any help would be appreciated 🙏

**Comment by afcarvalho1991** [comment]
That is weird, I haven't experienced anything like it. Can you share more details on how you access the host machine etc? I fear that the host machine might be the root cause for it.

**Comment by afcarvalho1991** [comment]
This is a crypto miner software. we found that the root cause for this is having:

1. basic username and password for the database
2. Having the database port exposed to the internet... which is always a bad idea and should never be done, please check your docker-compose.yaml check here: https://github.com/itmicus/cmdbuild_docker/blob/de17bcf169213dbe1c80ebf5b5afdeeb494c7fb9/3.4.1/docker-compose.yml#L12-L13 on production enviroments you should never have this port exposed...

**Comment by afcarvalho1991** [comment]
Perhaps,by default, we should disable exposing the DB port.
